### ISSUE TITLE
missing qid_map_dev.json for code/process_dev.py

### ISSUE THREAD

**Issue by e0003133** [rujunhan/TORQUE#4]
Hi,

I'm trying to run code/process_dev.py but there's a FileNotFoundError:

`Traceback (most recent call last):  
  File "code/process_dev.py", line 57, in <module>  
    with open('%s/qid_map_dev.json' % raw_path, 'r') as infile:  
FileNotFoundError: [Errno 2] No such file or directory: './raw//qid_map_dev.json'`

I checked the qiangning/TORQUE-dataset repo and there's only a qid_map.json.

Thanks

**Comment by rujunhan** [comment]
@qiangning would you mind pushing qid_map_dev.json into the dataset repo? Thanks.

**Comment by qiangning** [comment]
Thanks for the reminder. I have updated it: https://github.com/qiangning/TORQUE-dataset/blob/main/data/qid_map_dev.json

**Comment by e0003133** [comment]
thanks!
